# Generated by Django 4.0.6 on 2023-07-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_remove_profile_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlvote',
            name='position',
        ),
    ]
